routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// ROUTING WEB
Route::get('/', [App\Http\Controllers\WebController::class, 'index']);
Route::get('/kategori', [App\Http\Controllers\WebController::class, 'kategori']);
Route::get('/kategori/{slug}', [App\Http\Controllers\WebController::class, 'kategoriDetail'])->name('kategori.detail');
Route::get('/produk', [App\Http\Controllers\WebController::class, 'produk']);
Route::get('/produk/{slug}', [App\Http\Controllers\WebController::class, 'produkDetail'])->name('produk.detail');
Route::post('/produk/search', [App\Http\Controllers\WebController::class, 'produkSearch'])->name('produk.search');
Route::get('/keranjang/add/{produk_id}', [App\Http\Controllers\KeranjangController::class, 'addCart'])->name('keranjang.add');

Auth::routes();

// ROUTING USER PEMBELI
Route::group(['middleware' => ['role:user']], function () {
    Route::get('/user/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/user/profile', [App\Http\Controllers\ProfileController::class, 'index']);
    Route::post('/user/profile', [App\Http\Controllers\ProfileController::class, 'changeProfile']);
    Route::get('/user/keranjang', [App\Http\Controllers\KeranjangController::class, 'listCart']);
    Route::get('/user/keranjang/delete/{id}', [App\Http\Controllers\KeranjangController::class, 'deleteCart'])->name('keranjang.delete');
    Route::get('/user/checkout', [App\Http\Controllers\KeranjangController::class, 'checkout']);
    Route::post('/user/checkout', [App\Http\Controllers\KeranjangController::class, 'createTransaction']);
    Route::get('/user/order', [App\Http\Controllers\OrderController::class, 'index']);
    Route::get('/user/order/detail/{id}', [App\Http\Controllers\OrderController::class, 'detail'])->name('order.detail');
});

// ROUTING ADMIN PENJUAL
Route::group(['middleware' => ['role:admin']], function () {
    Route::get('/admin/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::get('/admin/profile', [App\Http\Controllers\ProfileController::class, 'index']);
    Route::post('/admin/profile', [App\Http\Controllers\ProfileController::class, 'changeProfile']);
    Route::resource('/admin/kategori', App\Http\Controllers\KategoriController::class)->except('show');
    Route::resource('/admin/produk', App\Http\Controllers\ProdukController::class)->except('show');
    Route::get('/admin/transaksi', [App\Http\Controllers\TransaksiController::class, 'index']);
    Route::get('/admin/transaksi/detail/{id}', [App\Http\Controllers\TransaksiController::class, 'detail'])->name('transaksi.detail');
    Route::get('/admin/transaksi/detail/update/{id}', [App\Http\Controllers\TransaksiController::class, 'update'])->name('transaksi.update');
});

resources/views/admin/dashboard.blade.php
@extends('adminlte::page')

@section('title', config('app.name') . ' - Dashboard')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-3 col-6">
            <div class="small-box bg-info">
                <div class="inner">
                    <h3>{{ $TotalKategori }}</h3>
                    <p>Kategori</p>
                </div>
                <div class="icon">
                    <i class="fa fa-list-alt"></i>
                </div>
                <a href="{{ route('kategori.index') }}" class="small-box-footer">lebih banyak <i
                        class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-6">
            <div class="small-box bg-warning">
                <div class="inner">
                    <h3>{{ $TotalProduk }}</h3>
                    <p>Produk</p>
                </div>
                <div class="icon">
                    <i class="fa fa-box-open"></i>
                </div>
                <a href="{{ route('produk.index') }}" class="small-box-footer">lebih banyak <i
                        class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-6">
            <div class="small-box bg-danger">
                <div class="inner">
                    <h3>{{ $TotalTransaksi }}</h3>
                    <p>Transaksi</p>
                </div>
                <div class="icon">
                    <i class="fa fa-file-alt"></i>
                </div>
                <a href="{{ url('admin/transaksi') }}" class="small-box-footer">lebih banyak <i
                        class="fas fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-6">
            <div class="small-box bg-success">
                <div class="inner">
                    <h3>{{ $TotalUser }}</h3>
                    <p>User</p>
                </div>
                <div class="icon">
                    <i class="fa fa-users"></i>
                </div>
                <span class="small-box-footer">Pembeli <i class="fas fa-user"></i></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="fas fa-chart-line mr-1"></i>
                        Transaksi: {{ tanggalIndo($tanggalAwal) . ' - ' . tanggalIndo($tanggalAkhir) }}
                    </h3>
                </div>
                <div class="card-body">
                    {!! $chartTransaksi->container() !!}
                </div>
            </div>
        </div>
    </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js" charset="utf-8"></script>
    {!! $chartTransaksi->script() !!}
@endsection

resources/views/admin/profile.blade.php
@extends('adminlte::page')

@section('title', config('app.name').' - Profile')

@section('content')
<x-alert></x-alert>
<div class="card">
    <div class="card-header bg-white">
        <h3>Profile & Change Password</h3>
    </div>
    <div class="card-body">
        <form action="{{ url('admin/profile') }}" method="POST">
            @csrf
            <div class="form-group row">
                <label for="name" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="name" value="{{ Auth::user()->name }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="email" value="{{ Auth::user()->email }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-sm-2 col-form-label">Change Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" name="password" placeholder="***">
                    <small class="form-text text-danger">kosongkan jika tidak ingin diubah.</small>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-2">
                    <button type="submit" class="btn btn-primary">Save Change</button>
                </div>
            </div>
        </form>
    </div>
</div>
@stop