routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// ROUTING WEB
Route::get('/', [App\Http\Controllers\WebController::class, 'index']);
Route::get('/kategori', [App\Http\Controllers\WebController::class, 'kategori']);
Route::get('/kategori/{slug}', [App\Http\Controllers\WebController::class, 'kategoriDetail'])->name('kategori.detail');
Route::get('/produk', [App\Http\Controllers\WebController::class, 'produk']);
Route::get('/produk/{slug}', [App\Http\Controllers\WebController::class, 'produkDetail'])->name('produk.detail');
Route::post('/produk/search', [App\Http\Controllers\WebController::class, 'produkSearch'])->name('produk.search');
Route::get('/keranjang/add/{produk_id}', [App\Http\Controllers\KeranjangController::class, 'addCart'])->name('keranjang.add');

Auth::routes();

// ROUTING USER PEMBELI
Route::group(['middleware' => ['role:user']], function () {
    Route::get('/user/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/user/profile', [App\Http\Controllers\ProfileController::class, 'index']);
    Route::post('/user/profile', [App\Http\Controllers\ProfileController::class, 'changeProfile']);
    Route::get('/user/keranjang', [App\Http\Controllers\KeranjangController::class, 'listCart']);
    Route::get('/user/keranjang/delete/{id}', [App\Http\Controllers\KeranjangController::class, 'deleteCart'])->name('keranjang.delete');
    Route::get('/user/checkout', [App\Http\Controllers\KeranjangController::class, 'checkout']);
    Route::post('/user/checkout', [App\Http\Controllers\KeranjangController::class, 'createTransaction']);
    Route::get('/user/order', [App\Http\Controllers\OrderController::class, 'index']);
    Route::get('/user/order/detail/{id}', [App\Http\Controllers\OrderController::class, 'detail'])->name('order.detail');
});

// ROUTING ADMIN PENJUAL
Route::group(['middleware' => ['role:admin']], function () {
    Route::get('/admin/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::get('/admin/profile', [App\Http\Controllers\ProfileController::class, 'index']);
    Route::post('/admin/profile', [App\Http\Controllers\ProfileController::class, 'changeProfile']);
    Route::resource('/admin/kategori', App\Http\Controllers\KategoriController::class)->except('show');
    Route::resource('/admin/produk', App\Http\Controllers\ProdukController::class)->except('show');
    Route::get('/admin/transaksi', [App\Http\Controllers\TransaksiController::class, 'index']);
    Route::get('/admin/transaksi/detail/{id}', [App\Http\Controllers\TransaksiController::class, 'detail'])->name('transaksi.detail');
    Route::get('/admin/transaksi/detail/update/{id}', [App\Http\Controllers\TransaksiController::class, 'update'])->name('transaksi.update');
});

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $primaryKey = 'id_prd';

    protected $keyType = 'string';

    public $incrementing = false;

    public function kategori()
    {
        return $this->belongsTo('App\Models\Kategori', 'kat_id', 'id_kat');
    }

    public function detail()
    {
        return $this->hasOne(Produk::class, 'prd_id', 'id_prd');
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kategori;
use App\Models\Produk;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File as FacadesFile;
use Illuminate\Support\Str;

class ProdukController extends Controller
{
    public function index()
    {
        $parse['produks'] = Produk::latest()->get();
        return view('admin.produk.index', $parse);
    }

    public function create()
    {
        $parse['kategoris'] = Kategori::latest()->get();
        return view('admin.produk.create', $parse);
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'kategori' => 'required',
            'harga' => 'required|numeric',
            'stok' => 'required|numeric',
            'berat' => 'required|numeric',
            'gambar' => 'required|file|image|mimes:jpeg,png,jpg|max:1024',
            'deskripsi' => 'required',
        ]);

        // PROSES FILE GAMBAR
        $file = $request->file('gambar');
        $nameFile = 'Store-' . $file->getClientOriginalName();
        $file->move('img/produk', $nameFile);

        Produk::create([
            'id_prd' => Str::uuid(),
            'kat_id' => $request->kategori,
            'nm_prd' => Str::title($request->nama),
            'slug_prd' => Str::kebab($request->nama),
            'hrg_prd' => $request->harga,
            'stok_prd' => $request->stok,
            'brt_prd' => $request->berat,
            'gbr_prd' => $nameFile,
            'desk_prd' => $request->deskripsi,
        ]);

        return redirect()->route('produk.index')
            ->with('alert-primary', 'Selamat, produk berhasil ditambahkan');
    }

    public function edit($id)
    {
        $parse['produk'] = Produk::find($id);
        $parse['kategoris'] = Kategori::latest()->get();
        return view('admin.produk.edit', $parse);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required',
            'kategori' => 'required',
            'harga' => 'required|numeric',
            'stok' => 'required|numeric',
            'berat' => 'required|numeric',
            'gambar' => 'file|image|mimes:jpeg,png,jpg|max:1024',
            'deskripsi' => 'required',
        ]);

        $produk = Produk::find($id);

        // PROSES FILE GAMBAR
        if ($request->file('gambar') != '') {
            // delete file
            FacadesFile::delete('img/produk/' . $produk->gbr_prd);

            // move File
            $file = $request->file('gambar');
            $nameFile = 'Store-' . $file->getClientOriginalName();
            $file->move('img/produk', $nameFile);
        } else {
            $nameFile = $produk->gbr_prd;
        }

        $produk->update([
            'id_prd' => Str::uuid(),
            'kat_id' => $request->kategori,
            'nm_prd' => Str::title($request->nama),
            'slug_prd' => Str::kebab($request->nama),
            'hrg_prd' => $request->harga,
            'stok_prd' => $request->stok,
            'brt_prd' => $request->berat,
            'gbr_prd' => $nameFile,
            'desk_prd' => $request->deskripsi,
        ]);

        return redirect()->route('produk.index')
            ->with('alert-warning', 'Selamat, produk berhasil diubah');
    }

    public function destroy($id)
    {
        $produk = Produk::find($id);

        // delete file
        FacadesFile::delete('img/produk/' . $produk->gbr_prd);

        $produk->delete();

        return redirect()->route('produk.index')
            ->with('alert-danger', 'Selamat, produk berhasil dihapus');
    }
}

resources/views/admin/produk/create.blade.php
@extends('adminlte::page')

@section('title', config('app.name').' - Produk')

@section('content')
<div class="card">
    <div class="card-header bg-white">
        <h4 class="my-auto d-flex justify-content-between">
            Tambah Data Produk
        </h4>
    </div>
    <div class="card-body">
        <form action="{{ route('produk.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group row">
                <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" placeholder="T-shirt, Clock, etc" value="{{ old('nama') }}">
                    @error('nama') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="kategori" class="col-sm-2 col-form-label">Kategori</label>
                <div class="col-sm-6">
                    <select class="custom-select @error('kategori') is-invalid @enderror" name="kategori">
                        <option selected value="">pilih kategori</option>
                        @foreach ($kategoris as $ktg)
                            <option value="{{ $ktg->id_kat }}" {{ (old('kategori') == $ktg->id_kat) ? 'selected' : '' }}>
                                {{ $ktg->nm_kat }}
                            </option>
                        @endforeach
                    </select>
                    @error('kategori') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="harga" class="col-sm-2 col-form-label">Harga</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control @error('harga') is-invalid @enderror" name="harga" placeholder="15000" value="{{ old('harga') }}">
                    @error('harga') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="stok" class="col-sm-2 col-form-label">Stok</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control @error('stok') is-invalid @enderror" name="stok" placeholder="0" value="{{ old('stok') }}">
                    @error('stok') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="berat" class="col-sm-2 col-form-label">Berat</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control @error('berat') is-invalid @enderror" name="berat" placeholder="dalam hitungan gram" value="{{ old('berat') }}">
                    @error('berat') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="gambar" class="col-sm-2 col-form-label">Gambar</label>
                <div class="col-sm-2">
                    <img src="{{ asset('img/produk/default.png')}}" class="img-thumbnail img-preview" alt="">
                </div>
                <div class="col-sm-8">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input @error('gambar') is-invalid @enderror" name="gambar" id="gambar" onchange="imgPreview()">
                        @error('gambar')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                        <label class="custom-file-label" for="gambar">pilih gambar produk</label>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label for="deskripsi" class="col-sm-2 col-form-label">Deskripsi</label>
                <div class="col-sm-10">
                    <textarea row="3" class="form-control @error('deskripsi') is-invalid @enderror" name="deskripsi" id="deskripsi">{{ old('deskripsi') }}</textarea>
                    @error('deskripsi') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-2">
                    <button type="submit" class="btn btn-primary">Save Change</button>
                </div>
            </div>
        </form>
    </div>
</div>
@stop

@section('css')
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
@stop

@section('js')
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script>
    function imgPreview() {
        const gambar = document.querySelector('#gambar');
        const gambarLabel = document.querySelector('.custom-file-label');
        const gambarPreview = document.querySelector('.img-preview');

        gambarLabel.textContent = gambar.files[0].name;

        const fileGambar = new FileReader();
        fileGambar.readAsDataURL(gambar.files[0]);
        fileGambar.onload = function(e) {
        gambarPreview.src = e.target.result;
        }
    }

    $('#deskripsi').summernote({
        placeholder: 'tulikan deskripsi dan tidak boleh kosong',
        height: 100
      });
</script>
@stop

resources/views/admin/produk/edit.blade.php
@extends('adminlte::page')

@section('title', config('app.name').' - Produk')

@section('content')
<div class="card">
    <div class="card-header bg-white">
        <h4 class="my-auto d-flex justify-content-between">
            Ubah Data Produk
        </h4>
    </div>
    <div class="card-body">
        <form action="{{ route('produk.update', ['produk'=>$produk->id_prd]) }}" method="POST" enctype="multipart/form-data">
            @csrf  @method('PUT')
            <div class="form-group row">
                <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" value="{{ $produk->nm_prd}}">
                    @error('nama') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="kategori" class="col-sm-2 col-form-label">Kategori</label>
                <div class="col-sm-6">
                    <select class="custom-select @error('kategori') is-invalid @enderror" name="kategori">
                        <option selected value="">pilih kategori</option>
                        @foreach ($kategoris as $ktg)
                            <option value="{{ $ktg->id_kat }}" {{ ($produk->kat_id == $ktg->id_kat) ? 'selected' : '' }}>
                                {{ $ktg->nm_kat }}
                            </option>
                        @endforeach
                    </select>
                    @error('kategori') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="harga" class="col-sm-2 col-form-label">Harga</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control @error('harga') is-invalid @enderror" name="harga" value="{{ $produk->hrg_prd }}">
                    @error('harga') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="stok" class="col-sm-2 col-form-label">Stok</label>
                <div class="col-sm-3">
                    <input type="text" class="form-control @error('stok') is-invalid @enderror" name="stok" value="{{ $produk->stok_prd }}">
                    @error('stok') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="berat" class="col-sm-2 col-form-label">Berat</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control @error('berat') is-invalid @enderror" name="berat" value="{{ $produk->brt_prd }}">
                    @error('berat') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <label for="gambar" class="col-sm-2 col-form-label">Gambar</label>
                <div class="col-sm-2">
                    <img src="{{ asset('img/produk/'. $produk->gbr_prd )}}" class="img-thumbnail img-preview" alt="">
                </div>
                <div class="col-sm-8">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input @error('gambar') is-invalid @enderror" name="gambar" id="gambar" onchange="imgPreview()">
                        @error('gambar')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                        <label class="custom-file-label" for="gambar">kosongkan jika tidak ingin mengubah gambar</label>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <label for="deskripsi" class="col-sm-2 col-form-label">Deskripsi</label>
                <div class="col-sm-10">
                    <textarea row="3" class="form-control @error('deskripsi') is-invalid @enderror" name="deskripsi" id="deskripsi">{{ $produk->desk_prd }}</textarea>
                    @error('deskripsi') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-2">
                    <button type="submit" class="btn btn-primary">Save Change</button>
                </div>
            </div>
        </form>
    </div>
</div>
@stop

@section('css')
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
@stop

@section('js')
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
<script>
    function imgPreview() {
        const gambar = document.querySelector('#gambar');
        const gambarLabel = document.querySelector('.custom-file-label');
        const gambarPreview = document.querySelector('.img-preview');

        gambarLabel.textContent = gambar.files[0].name;

        const fileGambar = new FileReader();
        fileGambar.readAsDataURL(gambar.files[0]);
        fileGambar.onload = function(e) {
        gambarPreview.src = e.target.result;
        }
    }

    $('#deskripsi').summernote({
        placeholder: 'tulikan deskripsi dan tidak boleh kosong',
        height: 100
      });
</script>
@stop

resources/views/admin/produk/index.blade.php
@extends('adminlte::page')

@section('title', config('app.name').' - Produk')

@section('content')
<x-alert></x-alert>
<div class="card">
    <div class="card-header bg-white">
        <h4 class="my-auto d-flex justify-content-between">
          Daftar Data Produk
          <a href="{{ route('produk.create') }}" class="btn btn-primary">Create Data</a>
        </h4>
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col" class="text-center" width="5%">#</th>
            <th scope="col" width="15%">Gambar</th>
            <th scope="col">Nama Produk</th>
            <th scope="col" width="15%">Harga</th>
            <th scope="col" width="10%">Stok</th>
            <th scope="col" width="15%">Action</th>
          </tr>
        </thead>
        <tbody>
          @php $no = 1 @endphp
          @foreach ($produks as $prd)
          <tr>
            <th scope="row" class="text-center">{{ $no++ }}</th>
            <td><img src="{{ asset('img/produk/'.$prd->gbr_prd) }}" alt="..." class="img-thumbnail"></td>
            <td>
              {{ $prd->nm_prd }} <br> 
              {{-- badge untuk kategori --}}
              <span class="badge badge-success">{{ $prd->kategori->nm_kat }}</span>
            </td>
            <td class="text-right">Rp. {{ $prd->hrg_prd }}</td>
            <td class="text-right">{{ $prd->stok_prd }}</td>
            <td class="text-center">
              <a href="{{ route('produk.edit', ['produk'=>$prd->id_prd]) }}" class="btn btn-sm btn-warning">Edit</a>
              <a class="btn btn-sm btn-danger d-inline" href="{{ route('produk.destroy', ['produk'=>$prd->id_prd]) }}" onclick="event.preventDefault(); document.getElementById('deleteData').submit();">
                  Delete
              </a>
              <form id="deleteData" action="{{ route('produk.destroy', ['produk'=>$prd->id_prd]) }}" method="POST" class="d-none">
                  @csrf @method('DELETE')
              </form>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
</div>
@stop