routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

// ROUTING WEB
Route::get('/', [App\Http\Controllers\WebController::class, 'index']);
Route::get('/kategori', [App\Http\Controllers\WebController::class, 'kategori']);
Route::get('/kategori/{slug}', [App\Http\Controllers\WebController::class, 'kategoriDetail'])->name('kategori.detail');
Route::get('/produk', [App\Http\Controllers\WebController::class, 'produk']);
Route::get('/produk/{slug}', [App\Http\Controllers\WebController::class, 'produkDetail'])->name('produk.detail');
Route::post('/produk/search', [App\Http\Controllers\WebController::class, 'produkSearch'])->name('produk.search');
Route::get('/keranjang/add/{produk_id}', [App\Http\Controllers\KeranjangController::class, 'addCart'])->name('keranjang.add');

Auth::routes();

// ROUTING USER PEMBELI
Route::group(['middleware' => ['role:user']], function () {
    Route::get('/user/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('/user/profile', [App\Http\Controllers\ProfileController::class, 'index']);
    Route::post('/user/profile', [App\Http\Controllers\ProfileController::class, 'changeProfile']);
    Route::get('/user/keranjang', [App\Http\Controllers\KeranjangController::class, 'listCart']);
    Route::get('/user/keranjang/delete/{id}', [App\Http\Controllers\KeranjangController::class, 'deleteCart'])->name('keranjang.delete');
    Route::get('/user/checkout', [App\Http\Controllers\KeranjangController::class, 'checkout']);
    Route::post('/user/checkout', [App\Http\Controllers\KeranjangController::class, 'createTransaction']);
    Route::get('/user/order', [App\Http\Controllers\OrderController::class, 'index']);
    Route::get('/user/order/detail/{id}', [App\Http\Controllers\OrderController::class, 'detail'])->name('order.detail');
});

// ROUTING ADMIN PENJUAL
Route::group(['middleware' => ['role:admin']], function () {
    Route::get('/admin/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::get('/admin/profile', [App\Http\Controllers\ProfileController::class, 'index']);
    Route::post('/admin/profile', [App\Http\Controllers\ProfileController::class, 'changeProfile']);
    Route::resource('/admin/kategori', App\Http\Controllers\KategoriController::class)->except('show');
    Route::resource('/admin/produk', App\Http\Controllers\ProdukController::class)->except('show');
    Route::get('/admin/transaksi', [App\Http\Controllers\TransaksiController::class, 'index']);
    Route::get('/admin/transaksi/detail/{id}', [App\Http\Controllers\TransaksiController::class, 'detail'])->name('transaksi.detail');
    Route::get('/admin/transaksi/detail/update/{id}', [App\Http\Controllers\TransaksiController::class, 'update'])->name('transaksi.update');
});

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $primaryKey = 'id_kat';

    protected $keyType = 'string';

    public $incrementing = false;

    public function produks()
    {
        return $this->hasMany('App\Models\Produk', 'kat_id', 'id_kat');
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kategori;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class KategoriController extends Controller
{

    public function index()
    {
        $parse['kategoris'] = Kategori::latest()->get();
        return view('admin.kategori.index', $parse);
    }

    public function create()
    {
        return view('admin.kategori.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required'
        ]);

        Kategori::create([
            'id_kat' => Str::uuid(),
            'nm_kat' => Str::title($request->nama),
            'slug_kat' => Str::kebab($request->nama)
        ]);

        return redirect()->route('kategori.index')
            ->with('alert-primary', 'Selamat, kategori berhasil ditambah kan');
    }

    public function edit($id)
    {
        $parse['kategori'] = Kategori::find($id);
        return view('admin.kategori.edit', $parse);
    }

    public function update(Request $request, $id)
    {
        Kategori::find($id)->update([
            'nm_kat' => Str::title($request->nama),
            'slug_kat' => Str::kebab($request->nama)
        ]);

        return redirect()->route('kategori.index')
            ->with('alert-warning', 'Selamat, kategori berhasil diubah');
    }

    public function destroy($id)
    {
        Kategori::find($id)->delete();
        return redirect()->route('kategori.index')
            ->with('alert-danger', 'Selamat, kategori berhasil dihapus');
    }
}

resources/views/admin/kategori/create.blade.php
@extends('adminlte::page')

@section('title', config('app.name').' - Kategori')

@section('content')
<x-alert></x-alert>
<div class="card">
    <div class="card-header bg-white">
        <h4 class="my-auto d-flex justify-content-between">
            Tambah Data Kategori
        </h4>
    </div>
    <div class="card-body">
        <form action="{{ route('kategori.store') }}" method="POST">
            @csrf
            <div class="form-group row">
                <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama" placeholder="T-shirt, Clock, etc">
                    @error('nama') 
                    <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-2">
                    <button type="submit" class="btn btn-primary">Save Change</button>
                </div>
            </div>
        </form>
    </div>
</div>
@stop

resources/views/admin/kategori/edit.blade.php
@extends('adminlte::page')

@section('title', config('app.name').' - Kategori')

@section('content')
<x-alert></x-alert>
<div class="card">
    <div class="card-header bg-white">
        <h4 class="my-auto d-flex justify-content-between">
        Ubah Data Kategori
        </h4>
    </div>
    <div class="card-body">
        <form action="{{ route('kategori.update', ['kategori'=>$kategori->id_kat]) }}" method="POST">
            @csrf @method('PUT')
            <div class="form-group row">
                <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="nama" value="{{ $kategori->nm_kat }}">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10 offset-2">
                    <button type="submit" class="btn btn-primary">Save Change</button>
                </div>
            </div>
        </form>
    </div>
</div>
@stop

resources/views/admin/kategori/index.blade.php
@extends('adminlte::page')

@section('title', config('app.name').' - Kategori')

@section('content')
<x-alert></x-alert>
<div class="card">
    <div class="card-header bg-white">
        <h4 class="my-auto d-flex justify-content-between">
          Daftar Data Kategori
          <a href="{{ route('kategori.create') }}" class="btn btn-primary">Create Data</a>
        </h4>
    </div>
    <div class="card-body">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col" class="text-center" width="5%">#</th>
            <th scope="col">Nama Kategori</th>
            <th scope="col">Slug</th>
            <th scope="col" width="15%">Action</th>
          </tr>
        </thead>
        <tbody>
          @php $no = 1 @endphp
          @foreach ($kategoris as $ktg)
          <tr>
            <th scope="row" class="text-center">{{ $no++ }}</th>
            <td>{{ $ktg->nm_kat }}</td>
            <td>{{ $ktg->slug_kat }}</td>
            <td class="text-center">
              <a href="{{ route('kategori.edit', ['kategori'=>$ktg->id_kat]) }}" class="btn btn-sm btn-warning">Edit</a>
              <a class="btn btn-sm btn-danger d-inline" href="{{ route('kategori.destroy', ['kategori'=>$ktg->id_kat]) }}" onclick="event.preventDefault(); document.getElementById('deleteData').submit();">
                  Delete
              </a>
              <form id="deleteData" action="{{ route('kategori.destroy', ['kategori'=>$ktg->id_kat]) }}" method="POST" class="d-none">
                  @csrf @method('DELETE')
              </form>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
</div>
@stop